//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SShopApp.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productid { get; set; }
        public string productname { get; set; }
        public int supplierid { get; set; }
        public int categoryid { get; set; }
        public decimal unitprice { get; set; }
        public bool discontinued { get; set; }
        public System.DateTime creation_date { get; set; }
        public int creation_user { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> modify_user { get; set; }
        public Nullable<int> delete_user { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public bool deleted { get; set; }
    }
}
