//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SShopApp.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public int shipperid { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string postalcode { get; set; }
        public Nullable<int> country { get; set; }
        public System.DateTime creation_date { get; set; }
        public int creation_user { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public Nullable<int> modify_user { get; set; }
        public Nullable<int> delete_user { get; set; }
        public Nullable<int> delete_date { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
